apiVersion: apps/v1
kind: Deployment
metadata:
  name: existing-mono-inrepo-noport-noingress-autodeploy-20250826090320
  labels:
    app: existing-mono-inrepo-noport-noingress-autodeploy-20250826090320
spec:
  replicas: 1
  selector:
    matchLabels:
      app: existing-mono-inrepo-noport-noingress-autodeploy-20250826090320
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-image-pull-secret
      containers:
      - name: existing-mono-inrepo-noport-noingress-autodeploy-20250826090320
        image: ghcr.io/fake-org/fake-registry/existing-mono-inrepo-noport-noingress-autodeploy-20250826090320:latest
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: existing-mono-inrepo-noport-noingress-autodeploy-20250826090320-container-vars
    metadata:
      labels:
        app: existing-mono-inrepo-noport-noingress-autodeploy-20250826090320
